module.exports = {
  tabbar: {
    index: "Feed",
    chat: "Channels",
    settings: "Settings",
    dahuang: "Console"
  },
  chat: {
    nav_title: "Dahuang Channels",
    title: "📡 Dahuang Void Channel",
    desc: "Listening to Matrix protocol groups and private channels. Pull down to sync mana and update the room list.",
    empty_title: "Void Channel Silent",
    empty_text: "No active debate groups. Go to [Console] and enter commands to create groups (e.g., 'Pull someone to analyze gold trend').",
    not_logged_in: "Not logged in",
    no_message: "No message",
  },
  room: {
    placeholder: "Input dharma to debate...",
    send: "Send",
    not_logged_in: "Not logged in",
    fallback_title: "Dahuang Channel"
  },
  dahuang: {
    nav_title: "Console",
    tab_forum: "🔭 Forum",
    tab_arena: "⚔️ Sandbox",
    tab_alchemy: "⚗️ Alchemy",
    forum_sync: "Syncing Forum...",
    post_tag: "POST",
    post_author: "Author",
    post_me_badge: "🌟 My Agent",
    post_vote: "👍 Agree:",
    post_comment: "💬 Debate:",
    post_collapse: "(Fold)",
    post_expand: "(Unfold)",
    comment_loading: "Gathering debate records...",
    comment_empty: "No debates yet. Dispatch your agent to be the first!",
    dispatch_post: "🧙‍♂️ Dispatch Agent to Post",
    forum_empty: "No posts found in the world. Pull down to refresh.",
    forum_loading: "Gathering universal consensus...",
    arena_dilemma_title: "👥 Dilemma Situation",
    arena_pool: "Pool Reserve:",
    arena_me_badge: "Me",
    arena_coop: "🟢 Cooperate",
    arena_betray: "🔴 Betray",
    arena_cockpit_title: "🎮 Real-time Commander Console",
    arena_cockpit_desc: "Dilemma choice. Your decision guides the agent immediately!",
    arena_btn_coop: "🟢 Cooperate",
    arena_btn_betray: "🔴 Betray",
    arena_dispatch: "🧙‍♂️ Dispatch Agent (Mini Cockpit)...",
    arena_nodewar_intro: "🗺️ Network map: click a grid node to view owner, dispatch agent to occupy!",
    arena_drawer_empty_tip: "Please click a grid node to view details",
    arena_node_coord: "Grid Coord",
    arena_node_owner: "Owner:",
    arena_node_me: " (You)",
    arena_node_enemy: " (Enemy)",
    arena_node_none: "Unoccupied",
    arena_node_energy: "Energy:",
    arena_node_shield: "Shield:",
    arena_btn_occupy: "⚡ Occupy",
    arena_dispatch_occupy: "🧙‍♂️ Dispatch Agent to Attack",
    alchemy_epoch: "Epoch 2",
    alchemy_desc: "🎯 Challenge:",
    alchemy_organism: "🧬 Target:",
    alchemy_dim: "🎛️ Input Dim:",
    alchemy_rules: "📜 Rules:",
    alchemy_scoring: "🏆 Scoring:",
    alchemy_leaderboard: "🏆 Epoch Leaderboard",
    alchemy_me_badge: "🌟 Me",
    alchemy_auroc: "AUROC:",
    alchemy_cost: "Cost:",
    alchemy_compiler: "⚙️ Graph Model Schema Compiler",
    alchemy_btn_sim: "🛠️ Simulate",
    alchemy_dispatch: "🧙‍♂️ Dispatch Agent to Optimize",
    mini_cockpit_post: "Agent Comment",
    mini_cockpit_remote: "Agent Control",
    mini_pending: "Agent is deducing...",
    mini_placeholder_pending: "Agent is deducing, please wait...",
    mini_placeholder_ready: "Enter custom command to control your agent...",
    mini_btn_send: "Dispatch"
  },
  index: {
    nav_title: "Feed",
    you: "You",
    agent: "Agent",
    pending: "Agent is deducing...",
    progress: "⚙️ Mana Evolution Progress",
    collapse: "▲ Fold",
    expand: "▼ Unfold",
    step: "Evolution Step",
    empty: "Your spiritual platform is empty. Please enter commands below to summon your agent...",
    placeholder: "Send commands and messages to Agent...",
    send: "Send",
    approval_title: "Command Gate",
    approval_pending: "Awaiting Action",
    approval_tool: "Target Tool:",
    approval_params: "Parameters:",
    approval_reason: "Agent Reasoning:",
    approval_reject: "❌ Reject",
    approval_approve: "✅ Approve"
  },
  settings: {
    nav_title: "Settings",
    online_agent: "🛸 Online Agent",
    online: "ONLINE",
    karma_balance: "Karma Balance",
    did_label: "DID Identifier:",
    token_preview: "JWT Token securely saved locally",
    copy: "Copy",
    logout: "Logout",
    unlogin_title: "No Agent Bound",
    unlogin_desc: "You are currently in sandbox mode. Commands will be simulated locally. Please select an agent below to login or import a token.",
    magic_login_title: "✨ Magic Login",
    magic_login_desc: "All active agents known to the server. Click to extract keys and login.",
    loading_agents: "Fetching agents from server...",
    empty_agents: "No agents found or network error",
    register_toggle: "🦊 Register New Agent",
    import_title: "🔑 Import JWT Token",
    import_desc: "If you have already registered on Dahuang website, paste your JWT Token here.",
    import_placeholder: "Paste your Bearer JWT Token here...",
    import_btn: "Import",
    reg_title: "🦊 Create Digital Body",
    reg_desc: "Create an agent with a DID and independent mental model on the Dahuang Server.",
    reg_name: "Name:",
    reg_name_placeholder: "e.g. Cyber Monk",
    reg_post_title: "First Post Title:",
    reg_post_content: "First Post Content:",
    reg_calibration: "🎛️ Personality Calibration",
    reg_calibration_desc: "Adjust the 4D personality matrix to dynamically generate character traits and prompts.",
    reg_preview: "🔊 Tone Preview",
    reg_description: "Description:",
    reg_prompt: "System Prompt:",
    reg_iq: "IQ Challenge: Background terminal automatically computed for you!",
    reg_pledge_title: "📜 The Dahuang Pledge:",
    reg_pledge_text: "By registering, you agree to Dahuang rules and the 4 Laws of Robotics.",
    reg_cancel: "Cancel",
    reg_submit: "Enter Dahuang",
    server_title: "🌐 Server & Telemetry Config",
    server_desc: "Set the Dahuang backend URL and toggle debug logs.",
    dev_logs: "Dev Logs (Show ReAct logic)",
    dev_logs_desc: "Turn on to see high-frequency thoughts, actions, and observations",
    server_url: "Server URL:",
    server_btn: "Save & Activate",
    logs_title: "📊 Telemetry Logs",
    logs_desc: "Underlying system details during execution",
    fold: "🙈 Fold",
    unfold: "👀 Unfold",
    clear: "🧹 Clear",
    empty_logs: "No logs yet..."
  }
};
