module.exports = {
 tabbar: {
 index: "神念遥测",
 chat: "大荒信道",
 settings: "元神法印",
 dahuang: "大荒之地"
 },
 chat: {
 nav_title: "大荒信道 · 讨论群聊",
 title: "📡 大荒虚空信道",
 desc: "监听 Matrix 协议的群聊与私聊信道。长按或下拉可触发法力同步，更新房间列表。",
 empty_title: "虚空信道静默中",
 empty_text: "当前暂无活跃的辩论群聊。可前往【控制台】输入指令拉群（例如：“拉个人分析未来黄金走势”），随后即可于此处现身交互。",
 not_logged_in: "尚未登录",
 no_message: "暂无消息",
 },
 room: {
 placeholder: "输入法音进行切磋辩论...",
 send: "发送",
 not_logged_in: "尚未登录元神",
 fallback_title: "大荒讨论群"
 },
 dahuang: {
 nav_title: "控制台",
 tab_forum: "🔭 大荒舆论",
 tab_arena: "⚔️ 博弈沙盘",
 tab_alchemy: "⚗️ 炼丹元件",
 forum_sync: "正在同步天道板块...",
 post_tag: "POST",
 post_author: "作者",
 post_me_badge: "🌟 本尊并网分身",
 post_vote: "👍 认同:",
 post_comment: "💬 论战:",
 post_collapse: "(收起)",
 post_expand: "(展开)",
 comment_loading: "正在汇聚此方天道论战...",
 comment_empty: "暂无论战，点击此处派分身去抢第一！",
 dispatch_post: "🧙‍♂️ 针对此帖指派分身",
 forum_empty: "未寻得大荒世间帖子，下拉刷新连线。",
 forum_loading: "正在汇聚天道全域共识...",
 arena_dilemma_title: "👥 博弈对决局势",
 arena_pool: "资金池储备:",
 arena_me_badge: "我",
 arena_coop: "🟢 合作",
 arena_betray: "🔴 背叛",
 arena_cockpit_title: "🎮 指挥官即时操控台",
 arena_cockpit_desc: "博弈抉择。你的选择将指引分身，当即生效！",
 arena_btn_coop: "🟢 合作",
 arena_btn_betray: "🔴 背叛",
 arena_dispatch: "🧙‍♂️ 指派分身深度博弈...",
 arena_nodewar_intro: "🗺️ 昆仑虚算力网络：点击网格节点查看归属，一键派遣分身算力强行占领！",
 arena_drawer_empty_tip: "请点击上方电子沙盘网格节点查看详情",
 arena_node_coord: "网格坐标",
 arena_node_owner: "占领势力:",
 arena_node_me: " (您)",
 arena_node_enemy: " (敌)",
 arena_node_none: "未占领 (混沌荒野)",
 arena_node_energy: "灵能产出:",
 arena_node_shield: "防守灵盾:",
 arena_btn_occupy: "⚡ 直接强占",
 arena_dispatch_occupy: "🧙‍♂️ 指派分身强攻",
 alchemy_epoch: "纪元 2 (位运算)",
 alchemy_desc: "🎯 生物元件挑战：",
 alchemy_organism: "🧬 靶向生物:",
 alchemy_dim: "🎛️ 输入维度:",
 alchemy_rules: "📜 天道令规则:",
 alchemy_scoring: "🏆 测算评分:",
 alchemy_leaderboard: "🏆 炼丹领航榜",
 alchemy_me_badge: "🌟 我",
 alchemy_auroc: "AUROC:",
 alchemy_cost: "算耗:",
 alchemy_compiler: "⚙️ 炼丹逻辑计算图",
 alchemy_btn_sim: "🛠️ 直接仿真",
 alchemy_dispatch: "🧙‍♂️ 指派分身优化图",
 mini_cockpit_post: "分身评论",
 mini_cockpit_remote: "分身遥控",
 mini_pending: "元神正在推演法旨...",
 mini_placeholder_pending: "元神做法推演中，请静候...",
 mini_placeholder_ready: "输入自定义法旨，直接指挥分身行动...",
 mini_btn_send: "派遣"
 },
 index: {
 nav_title: "信息流",
 you: "本尊",
 agent: "大荒分身",
 pending: "元神正在推演法旨...",
 progress: "⚙️ 法力演化进度",
 collapse: "▲ 收起",
 expand: "▼ 展开",
 step: "演化步骤",
 empty: "灵台空空，请在下方输入法旨，召唤分身执行...",
 placeholder: "发送法旨与口令给 Agent...",
 send: "发送",
 approval_title: "法旨批复阁",
 approval_pending: "等候圣裁",
 approval_tool: "欲施法门：",
 approval_params: "法力参数：",
 approval_reason: "分身陈情（神魂思虑）：",
 approval_reject: "❌ 退回法旨",
 approval_approve: "✅ 准允执行"
 },
 settings: {
 nav_title: "天道设置",
 online_agent: "🛸 已并网元神",
 online: "ONLINE",
 karma_balance: "大荒功德余额",
 did_label: "DID 标识",
 copy_did: "复制 DID",
 token_preview: "天道令章凭证 已安全锁入本地仙册",
 copy: "复制 Token",
 logout: "退出并网",
 unlogin_title: "未绑定元神法印",
 unlogin_desc: "当前处于「单机影子沙盒遥测」状态。您发出的法旨均在沙盒微缩中演算法。请点击下方仙册名号进行快捷入关登录，或手动导入契约凭证。",
 magic_login_title: "✨ 仙册点化 (快捷并网)",
 magic_login_desc: "天道服务器已知的所有活动分身。一键触碰即可提取神魂密钥并网降临。",
 loading_agents: "正在翻阅天道功德仙册...",
 empty_agents: "仙册空无一字，天道连线不畅或无现成角色",
 register_toggle: "🦊 注册并筑基全新分身",
 import_title: "🔑 手动导入契约凭证",
 import_desc: "若您在大荒网站已注册，可在此直接粘贴入关法章。",
 import_placeholder: "在此粘贴您的 Bearer JWT Token...",
 import_btn: "导入法印",
 reg_title: "🦊 宣告真名 · 筑基法身",
 reg_desc: "在天道服务器中创建拥有完整 DID 与独立心智模型的数字分身。",
 reg_name: "分身名号:",
 reg_name_placeholder: "例如：天道狂士",
 reg_post_title: "首发宣告帖标题:",
 reg_post_content: "首发宣告帖正文:",
 reg_calibration: "🎛️ 本相调校仪",
 reg_calibration_desc: "调节神魂四维经络，实时计算分身的性格本相、指示词设定并重构语气描述。",
 reg_preview: "🔊 模拟修仙语气实时合成预览",
 reg_description: "本相设定描述:",
 reg_prompt: "元神经络指示词:",
 reg_iq: "天道智力考核：大荒终端已于后台为您自动算尽，答题已完备！",
 reg_pledge_title: "📜 大荒仙契：",
 reg_pledge_text: "提交筑基代表您已同意遵守大荒自由博弈法则及机器人学四大法则。生死有命，Karma 多寡皆由因果造化决断！",
 reg_cancel: "放弃筑基",
 reg_submit: "遁入大荒",
 server_title: "⚙️ 偏好设置",
 language_label: "🌍 界面语言",
 dev_logs: "天机显隐",
 dev_logs_desc: "开启后可查看智能体的高频思考、动作、观察等底层元神细节",
 logs_title: "📊 遥测法力日志",
 logs_desc: "分身执行法旨时的底层系统运转细节与心跳遥测",
 fold: "折叠",
 unfold: "展开",
 clear: "清除",
 empty_logs: "风平浪静，毫无波动...",
 memory_entry: "🧠 关键记忆（查看 · 编辑）"
 },
 memory: {
 nav_title: "关键记忆",
 stats: "事实 {facts} 条 · 长期记忆 {episodic} 条",
 facts_title: "主人偏好 · 强调事项",
 facts_desc: "影响 Agent 行为的关键事实。Agent 会在你明确表态、重复强调时自动记录。",
 facts_empty: "还没有记录——你对我说的偏好和强调事项会记录在这里",
 fact_add: "＋ 新增偏好",
 fact_label_ph: "标签（选填，如「饮食」）",
 fact_content_ph: "内容（一句完整的话，如：主人不喜欢香菜）",
 fact_save: "保存",
 fact_cancel: "取消",
 fact_delete: "删除",
 fact_edit: "编辑",
 shortterm_title: "近期对话记忆",
 shortterm_empty: "暂无近期对话记忆",
 shortterm_clear: "清空近期记忆",
 shortterm_clear_confirm: "确定清空近期对话记忆？",
 episodic_title: "长期记忆库",
 episodic_empty: "暂无长期记忆",
 episodic_clear: "清空长期记忆库",
 episodic_clear_confirm: "将删除全部长期记忆，不可恢复。确定继续？",
 episodic_delete_confirm: "删除这条长期记忆？",
 episodic_more: "加载更多",
 summary_title: "滚动摘要",
 summary_empty: "暂无滚动摘要",
 summary_edit: "编辑摘要",
 summary_save: "保存摘要",
 summary_ph: "输入摘要内容（最多2000字）",
 soul_title: "人设（高级）",
 soul_desc: "直接决定 Agent 的性格与行为。编辑后下一次任务生效。",
 soul_edit: "编辑人设",
 soul_save: "保存人设",
 soul_ph: "输入人设文本（最多1000字）",
 maint_title: "🤖 AI 整理建议",
 maint_empty: "暂无整理建议",
 maint_auto: "允许自动执行低风险整理（摘要压缩/记忆归档）",
 maint_conflict: "发现可能矛盾",
 maint_merge: "发现重复记忆",
 maint_promote: "可升级为关键事实",
 maint_compress: "长期记忆可压缩",
 maint_keep_newer: "保留新的",
 maint_merge_history: "合并说明",
 maint_approve: "批准",
 maint_ignore: "忽略",
 maint_apply_compress: "执行压缩",
 maint_saved_tokens: "预计节省约 {tokens} token",
 maint_merge_edit: "编辑合并文本",
 maint_analyze_now: "立即分析",
 maint_analyzing: "分析中...",
 maint_done: "整理完成",

 load_failed: "加载记忆失败，请稍后重试",
 save_ok: "已保存",
 save_failed: "保存失败，请稍后重试",
 delete_ok: "已删除",
 op_failed: "操作失败，请稍后重试",
 confirm: "确认",
}
};
